# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f06253d3a9b54ac3beae9e5b91f9ade02703d86892acfa33d459bddc06f97c456320bfc2eab69871e810f06f4b94a2ca9bb0117031cfd39507f7b840a7b98bb

test:
  secret_key_base: b13c864baa2de5da8f59998fea00a40c582b3f725d0d6d6778dc6f28909641decc66f8951bdd3b11d6df94153b87b0aaa2c995f4f5d4037cae95a12310b675c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
